configuration:  
  projectName: configclient
server:
  port: 8080
message:
  greeting: Hello from the default configuration!
management:
  security:
    enabled: false
---
spring:
  profiles: prod
configuration:  
  projectName: configclient
server:
  port: 9000
message:
  greeting: Hello from the prod environment!
