configuration:  
  projectName: configclient
server:
  port: 8080
message:
  greeting: Hello from the default configuration!
management:
  security:
    enabled: false
---
spring:
  profiles: dev
configuration:  
  projectName: configclient
server:
  port: 8000
message:
  greeting: Hello from the dev environment!
